[paper1]
date = 2022-01-01
title = "A Publication Title"
authors = "Nelson Bighetti, Jane Doe"
journal = "Some Journal"
url = "talks/example"
doi = ""

[paper2]
date = 2022-01-02
title = "A Publication Title"
authors = "Nelson Bighetti, Jane Doe"
journal = "Some Journal"
url = "talks/example"
doi = ""