name: Deploy Demo

on:
  push:
    branches:
      - main
      - makeIntoPackage # Delete this once ready to merge
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Julia
        uses: julia-actions/setup-julia@latest
      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run JS Code
        run: |
          cd demo
          mkdir _css
          npm install
          node ./utils/js/compile_sass.js
          node ./utils/js/generate_jdenticons.js
      - name: Build Franklin Site
        shell: julia --project=demo {0}
        run: |
          using Pkg
          Pkg.instantiate()
          using Franklin
          optimize(minify=false, prerender=false)
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: __site
